In [1]:
import numpy as np
import pandas as pd

In [40]:
df = pd.DataFrame({"col1":[1,2,3,4,5,6,7],"col2": [10,20,30,40,50,60,70],"col3":['21','22','23','24','25','26','27']})

In [32]:
df.dtypes

col1     int64
col2     int64
col3    object
dtype: object

In [6]:
df

col1  col2 col3
0     1    10   21
1     2    20   22
2     3    30   23
3     4    40   24
4     5    50   25
5     6    60   26
6     7    70   27

In [9]:
df.loc[[True,False,True,False,False,False,False],:]

col1  col2 col3
0     1    10   21
2     3    30   23

In [10]:
a = np.array([1,2,3,4,5,6,7,8,9])
a > 4

array([False, False, False, False,  True,  True,  True,  True,  True])

In [39]:
df["col1"]

0    1
1    2
2    3
3    4
4    5
5    6
6    7
Name: col1, dtype: int64

In [41]:
df["col3"] = pd.to_numeric(df.loc[:,"col3"])

In [42]:
df.dtypes

col1    int64
col2    int64
col3    int64
dtype: object

In [16]:
df.loc[df["col1"] > 4,"col3"] = df.loc[df["col1"] > 4,"col3"] * 100

In [46]:
a = np.random.random((10,6))
b = np.random.random((6,))
c = np.random.random((6,1))

In [48]:
b.shape
print(b)

[0.77373703 0.88445383 0.33497637 0.6027361  0.09636942 0.44187583]


In [49]:
print(c)

[[0.04610074]
 [0.77657836]
 [0.29526186]
 [0.02540334]
 [0.63068361]
 [0.07261732]]
